### ISSUE TITLE
Cannot build with Xcode 6.1.1; ARC forbids Objective-C objects in struct/union

### ISSUE THREAD

**Issue by Tatsh** [mlnlover11/SettingsKit#10]
I have the iOS 7.1 SDK installed, grabbed from Xcode 5.1.1. Does this combination work?

This file gets sourced in Bash:

```bash
export THEOS=$HOME/.theos
export PATH="$THEOS/bin:$PATH"
export SDKVERSION=7.1
export THEOS_DEVICE_IP=tatshphone
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
```

I am using rpetrich's version of Theos, with headers and everything up-to-date.

I get this for output when I use `make`:

```
Making all for framework SettingsKit...
 Copying resource directories into the framework wrapper...
 Compiling SKTintedControlCell.m (armv7)...
In file included from SKTintedControlCell.m:1:
In file included from ./SKTintedControlCell.h:1:
In file included from /Users/tatsh/.theos/include/Preferences/Preferences.h:11:
In file included from /Users/tatsh/.theos/include/Preferences/PSControlTableCell.h:8:
In file included from /Users/tatsh/.theos/include/Preferences/PSTableCell.h:10:
In file included from /Users/tatsh/.theos/include/UIKit/UIPreferencesTableCell.h:6:
In file included from /Users/tatsh/.theos/include/UIKit/UIImageAndTextTableCell.h:6:
In file included from /Users/tatsh/.theos/include/UIKit/UITableCell.h:6:
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:88:7: error: ARC forbids Objective-C objects in struct
                        id _field1;
                           ^
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:122:11: error: ARC forbids Objective-C objects in union
        UIImage* image;
                 ^
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:175:12: error: ARC forbids Objective-C objects in struct
        NSString* value;
                  ^
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:193:13: error: ARC forbids Objective-C objects in struct
        WAKWindow* _field2;
                   ^
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:243:5: error: ARC forbids Objective-C objects in struct
        id _field1;
           ^
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:281:12: error: ARC forbids Objective-C objects in struct
        NSString* previousKey[64];
                  ^
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:296:12: error: ARC forbids Objective-C objects in struct
        NSString* _field1;
                  ^
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:303:5: error: ARC forbids Objective-C objects in struct
        id _field1;
           ^
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:312:5: error: ARC forbids Objective-C objects in struct
        id _field3;
           ^
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:342:11: error: ARC forbids Objective-C objects in struct
        UIImage* background;
                 ^
/Users/tatsh/.theos/include/UIKit/UIKit-Structs.h:351:10: error: ARC forbids Objective-C objects in struct
        UIFont* _field1;
                ^
11 errors generated.
make[3]: *** [.theos/obj/armv7/SKTintedControlCell.m.c3f0d252.o] Error 1
make[2]: *** [.theos/obj/armv7/SettingsKit.framework/SettingsKit] Error 2
make[1]: *** [internal-framework-all_] Error 2
make: *** [SettingsKit.all.framework.variables] Error 2
```

It appears CFLAGS in `Makefile` is ignored? When I forcefully specify CFLAGS `make CFLAGS=-fobjc-arc`:

```
Making all for framework SettingsKit...
 Copying resource directories into the framework wrapper...
 Compiling SKTintedControlCell.m (armv7)...
In file included from SKTintedControlCell.m:1:
In file included from ./SKTintedControlCell.h:1:
In file included from /Users/tatsh/.theos/include/Preferences/Preferences.h:8:
In file included from /Users/tatsh/.theos/include/Preferences/Preferences-Structs.h:10:
In file included from /Users/tatsh/.theos/include/QuartzCore/QuartzCore2.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/QuartzCore.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CoreAnimation.h:30:
In file included from /Users/tatsh/.theos/include/QuartzCore/CAValueFunction.h:9:
In file included from /Users/tatsh/.theos/include/QuartzCore/QuartzCore-Structs.h:11:
/Users/tatsh/.theos/include/IOSurface/IOSurface.h:20:10: fatal error: 'IOSurface/IOSurfaceAPI.h' file not found
#include <IOSurface/IOSurfaceAPI.h>
         ^
1 error generated.
make[3]: *** [.theos/obj/armv7/SKTintedControlCell.m.241e3aa2.o] Error 1
make[2]: *** [.theos/obj/armv7/SettingsKit.framework/SettingsKit] Error 2
make[1]: *** [internal-framework-all_] Error 2
make: *** [SettingsKit.all.framework.variables] Error 2
```
